//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodePlex.TfsLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodePlex.TfsLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xs:schema id=&quot;IgnoreListSchema&quot;
        ///                  targetNamespace=&quot;http://www.codeplex.com/schema/IgnoreListSchema-1.0.xsd&quot;
        ///                  elementFormDefault=&quot;qualified&quot;
        ///                  xmlns=&quot;http://www.codeplex.com/schema/IgnoreListSchema-1.0.xsd&quot;
        ///                  xmlns:mstns=&quot;http://www.codeplex.com/schema/IgnoreListSchema-1.0.xsd&quot;
        ///                  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///  &lt;xs:complexType name=&quot;IgnoreElement&quot;&gt;
        ///    &lt;xs:sequenc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IgnoreListSchema {
            get {
                return ResourceManager.GetString("IgnoreListSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xs:schema id=&quot;PatchSchema&quot;
        ///                  targetNamespace=&quot;http://www.codeplex.com/schema/PatchSchema-1.0.xsd&quot;
        ///                  elementFormDefault=&quot;qualified&quot;
        ///                  xmlns=&quot;http://www.codeplex.com/schema/PatchSchema-1.0.xsd&quot;
        ///                  xmlns:mstns=&quot;http://www.codeplex.com/schema/PatchSchema-1.0.xsd&quot;
        ///                  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///  &lt;xs:complexType name=&quot;PatchElement&quot;&gt;
        ///    &lt;xs:sequence&gt;
        ///      &lt;xs:element [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PatchSchema {
            get {
                return ResourceManager.GetString("PatchSchema", resourceCulture);
            }
        }
    }
}
